[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"

# Polygon Amoy RPC
[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
